### ISSUE TITLE
loadTranslations is not a function

### ISSUE THREAD

**Issue by bnova-stefan** [samuelstroschein/inlang#16]
I get the following error if I try to use inlang in my sveltekit project. 

```
500
__vite_ssr_import_1__.loadTranslations is not a function
TypeError: __vite_ssr_import_1__.loadTranslations is not a function
    at load (__layout.svelte:9:38)
    at load_node (file:///Users/swelsch/Development/b-nova/breedium/frontend/node_modules/@sveltejs/kit/dist/ssr.js:957:30)
    at respond$1 (file:///Users/swelsch/Development/b-nova/breedium/frontend/node_modules/@sveltejs/kit/dist/ssr.js:1242:21)
    at async render_page (file:///Users/swelsch/Development/b-nova/breedium/frontend/node_modules/@sveltejs/kit/dist/ssr.js:1433:19)
    at async resolve (file:///Users/swelsch/Development/b-nova/breedium/frontend/node_modules/@sveltejs/kit/dist/ssr.js:1696:10)
    at async Object.handle (/Users/swelsch/Development/b-nova/breedium/frontend/src/hooks.ts:14:24)
    at async respond (file:///Users/swelsch/Development/b-nova/breedium/frontend/node_modules/@sveltejs/kit/dist/ssr.js:1675:10)
    at async svelteKitMiddleware (file:///Users/swelsch/Development/b-nova/breedium/frontend/node_modules/@sveltejs/kit/dist/chunks/index.js:4531:22)
```
I did `npm install inlang --save` and my __layout.svelte file looks like

```
<script lang="ts" context="module">
	import Header from '$lib/header/Header.svelte';

    import { setTranslations, loadTranslations } from 'inlang';

    export async function load({ page }) {
        if (page.params.lang) {
            setTranslations(
                await loadTranslations({
                    projectDomain: 'demo.sveltekit.inlang.dev',
                    locale: page.params.lang
                })
            );
        }
        return {};
    }
</script>
```

**Comment by samuelstroschein** [comment]
Hi Stefan,
we just changed how inlang works under the hood. Documentation will follow. I will keep you posted.

**Comment by samuelstroschein** [comment]
The documentation is done. You can find a demo video of the new approach [here](https://youtu.be/mivXTx-cpcM). 

If you just want to try it out yourself, the new [template repo](https://github.com/samuelstroschein/inlang-test-repository) is the right path.
